#!/bin/bash

if [ -z "$ENSTARTER_ORIGIN" ] ; then
   ENSTARTER_ORIGIN=~/.enstarter
fi

ENSTARTER_BIN=$ENSTARTER_ORIGIN/bin/enstarter
ENSTARTER_INSTALLS_DIR=$ENSTARTER_ORIGIN/installs
ENSTARTER_COMMANDS_DIR=$ENSTARTER_ORIGIN/commands

#TODO: need a build-script to output the repo_user, repo_name, and branch to this file
GITHUB_URL='nhemsley/enstarter'

[ ! -d $ENSTARTER_ORIGIN ] && git clone https://github.com/$GITHUB_URL.git $ENSTARTER_ORIGIN

$ENSTARTER_BIN install-self

$ENSTARTER_BIN install
