#!/bin/bash

if [ -z "$ENSTARTER_ORIGIN" ] then
   ENSTARTER_ORIGIN=~/.enstarter
fi

ENSTARTER_BIN=$ENSTARTER_ORIGIN/bin/enstarter
ENSTARTER_INSTALLS_DIR=$ENSTARTER_ORIGIN/installs
ENSTARTER_COMMANDS_DIR=$ENSTARTER_ORIGIN/commands

GITHUB_URL='nhemsley/enstarter'

[ ! -d $ENSTARTER_ORIGIN ] && git clone https://github.com/$GITHUB_URL.git $ENSTARTER_ORIGIN

$ENSTARTER_BIN --install
